### ISSUE TITLE
redis.exceptions.ConnectionError: Error 99 connecting to localhost:6379. Cannot assign requested address.

### ISSUE THREAD

**Issue by mgheorghe** [opencomputeproject/SAI-Challenger#107]
nice to have not critical issue
but if run.sh and then exec are executed one after the other all cases will fail with
`redis.exceptions.ConnectionError: Error 99 connecting to localhost:6379. Cannot assign requested address.`

if we wait 10sec or so between the commands than it it will pass
i assume run.sh  does not wait for redis service to start 

i believe docker allows a health check  and will be  good to add one

or try the commands from `https://github.com/opencomputeproject/SAI-Challenger/blob/main/docs/standalone_mode.md`
./run.sh -a trident2 -t saivs
./exec.sh -t saivs pytest --testbed=saivs_standalone -v -k api/test_vlan.py

this is needed because of https://github.com/opencomputeproject/SAI-Challenger/issues/99
`ERROR api/test_vlan.py::TestSaiVlan::test_vlan_create - AssertionError: SyncD has not started yet...`
whenever a test fails and causes syncd to go in a bad state we need to restart the containers and rerun next test.

**Comment by andriy-kokhan** [comment]
Expected to be resolved by PR #110 . Please feel free to reopen if still see the issue.
