### ISSUE TITLE
set operation for 2 attributes ignores the second attribute

### ISSUE THREAD

**Issue by selldinesh** [opencomputeproject/SAI-Challenger#174]
In the below code block. it seems the line containing   "SAI_PORT_ATTR_PORT_VLAN_ID", "10", doesn't seem to have any effect. the script behaves the same if we have it or don't have it on the same block. Some form of error needs to be thrown if the set operation doesn't complete as expected

def test_l2_traffic(npu, dataplane):
    """

    """
    commands = [
        {
            "name": "PORT_3",
            "op": "set",
            "type": "SAI_OBJECT_TYPE_PORT",
            "attributes": [
                "SAI_PORT_ATTR_ADMIN_STATE",
                "true",
                "SAI_PORT_ATTR_PORT_VLAN_ID",
                "10",
            ],
        },
    ]
    for command in commands:
        print("-" * 80)
        print(command)
        result = npu.command_processor.process_command(command)
        print(result)

**Comment by chrispsommers** [comment]
@selldinesh have you tried to observe SAI logs to see what happens when this configuration is applied? It might help in analysis.

**Comment by andriy-kokhan** [comment]
For all SAI objects, only one attribute can be set at a time.
E.g., 
```
typedef sai_status_t (*sai_set_port_attribute_fn)(
        _In_ sai_object_id_t port_id,
        _In_ const sai_attribute_t *attr);
```
Adding extra check in #176

**Comment by andriy-kokhan** [comment]
@selldinesh , the issue should be resolved now. Please confirm.

**Comment by andriy-kokhan** [comment]
Closing. Please feel free to reopen in case you still see an issue with this.
