### ISSUE TITLE
Set is PASSING but get is FAILING

### ISSUE THREAD

**Issue by selldinesh** [opencomputeproject/SAI-Challenger#190]
Below is the code snippet for set and get operation for SAI_ACL_COUNTER_ATTR_PACKETS

`from pprint import pprint

import pytest

class TestSaiWred:
    # object with no attributes

    def test_wred_create(self, npu):

        commands = [{'name': 'wred_1', 'op': 'create', 'type': 'SAI_OBJECT_TYPE_WRED', 'attributes': []}]

        results = [*npu.process_commands(commands)]
        print('======= SAI commands RETURN values create =======')
        pprint(results)

    @pytest.mark.dependency(name="test_sai_acl_counter_attr_packets_set")
    def test_sai_acl_counter_attr_packets_set(self, npu):

        commands = [
            {
                "name": "wred_1",
                "op": "set",
                "attributes": ["SAI_ACL_COUNTER_ATTR_PACKETS", '0']
            }
        ]
        results = [*npu.process_commands(commands)]
        print("======= SAI commands RETURN values get =======")
        pprint(results)
        assert all([result == 'SAI_STATUS_SUCCESS' for result in results]), 'Set error'

    @pytest.mark.dependency(depends=["test_sai_acl_counter_attr_packets_set"])
    def test_sai_acl_counter_attr_packets_get(self, npu):

        commands = [
            {
                "name": "wred_1",
                "op": "get",
                "type": "SAI_OBJECT_TYPE_WRED",
                "attributes": ["SAI_ACL_COUNTER_ATTR_PACKETS"]
            }
        ]
        results = [*npu.process_commands(commands)]
        print("======= SAI commands RETURN values get =======")
        pprint(results)
        r_value = results[0][0].value()
        print(r_value)`

On execution getting the following error which i couldn't follow, can you please explain what mistake i am doing here
This is the following error i got

`
test_wred.py::TestSaiWred::test_wred_create ======= SAI commands RETURN values create =======
['oid:0x130000000005ad']
PASSED
test_wred.py::TestSaiWred::test_sai_acl_counter_attr_packets_set ======= SAI commands RETURN values get =======
['SAI_STATUS_SUCCESS']
PASSED
test_wred.py::TestSaiWred::test_sai_acl_counter_attr_packets_get FAILED

======================================================================================================================================== FAILURES =========================================================================================================================================
____________________________________________________________________________________________________________________ TestSaiWred.test_sai_acl_counter_attr_packets_get ____________________________________________________________________________________________________________________

self = <test_wred.TestSaiWred object at 0x7f76f4bb18d0>, npu = <sai_npu.SaiNpuImpl object at 0x7f76f47b1a20>

    @pytest.mark.dependency(depends=["test_sai_acl_counter_attr_packets_set"])
    def test_sai_acl_counter_attr_packets_get(self, npu):
    
        commands = [
            {
                "name": "wred_1",
                "op": "get",
                "type": "SAI_OBJECT_TYPE_WRED",
                "attributes": ["SAI_ACL_COUNTER_ATTR_PACKETS"]
            }
        ]
>       results = [*npu.process_commands(commands)]

test_wred.py:48: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/usr/local/lib/python3.7/dist-packages/saichallenger/common/sai.py:201: in process_commands
    yield from map(self.command_processor.process_command, commands)
/usr/local/lib/python3.7/dist-packages/saichallenger/common/sai.py:150: in process_command
    status, data = self.sai.get_by_type(obj_id, attr, attr_type)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <sai_npu.SaiNpuImpl object at 0x7f76f47b1a20>, obj = 'oid:0x130000000005ad', attr = 'SAI_ACL_COUNTER_ATTR_PACKETS', attr_type = None, do_assert = False

    def get_by_type(self, obj, attr, attr_type, do_assert=False):
        # TODO: Check how to map these types into the struct or list
        unsupported_types = [
                                "sai_port_eye_values_list_t", "sai_prbs_rx_state_t",
                                "sai_port_err_status_list_t", "sai_fabric_port_reachability_t",
                                "sai_port_lane_latch_status_list_t", "sai_latch_status_t"
                            ]
        if attr_type == "sai_object_list_t":
            status, data = self.get(obj, [attr, "1:oid:0x0"], do_assert)
            if status == "SAI_STATUS_BUFFER_OVERFLOW":
                status, data = self.get(obj, [attr, self.make_list(data.uint32(), "oid:0x0")], do_assert)
        elif attr_type == "sai_s32_list_t" or attr_type == "sai_u32_list_t" or \
                attr_type == "sai_s16_list_t" or attr_type == "sai_u16_list_t" or\
                attr_type == "sai_s8_list_t" or attr_type == "sai_u8_list_t" or attr_type == "sai_vlan_list_t":
            status, data = self.get(obj, [attr, "1:0"], do_assert)
            if status == "SAI_STATUS_BUFFER_OVERFLOW":
                status, data = self.get(obj, [attr, self.make_list(data.uint32(), "0")], do_assert)
        elif attr_type == "sai_acl_capability_t":
            status, data = self.get(obj, [attr, self.make_acl_list(1)], do_assert)
            if status == "SAI_STATUS_BUFFER_OVERFLOW":
                # extract number of actions supported for the stage
                # e.g. ["SAI_SWITCH_ATTR_ACL_STAGE_EGRESS","true:51"] -> 51
                length = int(data.to_json()[1].split(":")[1])
                status, data = self.get(obj, [attr, self.make_acl_list(length)], do_assert)
        elif attr_type == "sai_acl_resource_list_t":
            status, data = self.get(obj, [attr, self.make_acl_resource_list(1)], do_assert)
            if status == "SAI_STATUS_BUFFER_OVERFLOW":
                # extract number of actions supported for the stage
                # e.g. ['SAI_SWITCH_ATTR_AVAILABLE_ACL_TABLE', '{"count":10,"list":null}'] -> 10
                length = json.loads(data.to_json()[1])["count"]
                status, data = self.get(obj, [attr, self.make_acl_resource_list(length)], do_assert)
        elif attr_type == "sai_map_list_t":
            status, data = self.get(obj, [attr, self.make_map_list(1)], do_assert)
            if status == "SAI_STATUS_BUFFER_OVERFLOW":
                length = json.loads(data.to_json()[1])["count"]
                status, data = self.get(obj, [attr, self.make_map_list(length)], do_assert)
        elif attr_type == "sai_system_port_config_list_t":
            status, data = self.get(obj, [attr, self.make_system_port_config_list(1)], do_assert)
            if status == "SAI_STATUS_BUFFER_OVERFLOW":
                length = json.loads(data.to_json()[1])["count"]
                status, data = self.get(obj, [attr, self.make_system_port_config_list(length)], do_assert)
        elif attr_type == "sai_object_id_t":
            status, data = self.get(obj, [attr, "oid:0x0"], do_assert)
        elif attr_type == "bool":
            status, data = self.get(obj, [attr, "true"], do_assert)
        elif attr_type == "sai_mac_t":
            status, data = self.get(obj, [attr, "00:00:00:00:00:00"], do_assert)
        elif attr_type == "sai_ip_address_t":
            status, data = self.get(obj, [attr, "0.0.0.0"], do_assert)
        elif attr_type == "sai_ip4_t":
            status, data = self.get(obj, [attr, "0.0.0.0&mask:0.0.0.0"], do_assert)
        elif attr_type == "sai_ip6_t":
            status, data = self.get(obj, [attr, "::0.0.0.0&mask:0:0:0:0:0:0:0:0"], do_assert)
        elif attr_type == "sai_u32_range_t" or attr_type == "sai_s32_range_t":
            status, data = self.get(obj, [attr, "0,0"], do_assert)
        elif attr_type in unsupported_types:
            status, data = f"SAI-C internal failure. Unsupported type {attr_type}", None
>       elif attr_type.startswith("sai_") or attr_type == "" or attr_type == "char":
E       AttributeError: 'NoneType' object has no attribute 'startswith'

/usr/local/lib/python3.7/dist-packages/saichallenger/common/sai.py:373: AttributeError
---------------------------------------------------------------------------------------------------------------------------------- Captured log teardown ----------------------------------------------------------------------------------------------------------------------------------
INFO     dataplane:dataplane.py:667 Thread exit
==================================================================================================================================== warnings summary =====================================================================================================================================
tests/test_wred.py::TestSaiWred::test_wred_create
  /usr/lib/python3/dist-packages/paramiko/kex_ecdh_nist.py:39: CryptographyDeprecationWarning: encode_point has been deprecated on EllipticCurvePublicNumbers and will be removed in a future version. Please use EllipticCurvePublicKey.public_bytes to obtain both compressed and uncompressed point encoding.
    m.add_string(self.Q_C.public_numbers().encode_point())

tests/test_wred.py::TestSaiWred::test_wred_create
  /usr/lib/python3/dist-packages/paramiko/kex_ecdh_nist.py:96: CryptographyDeprecationWarning: Support for unsafe construction of public numbers from encoded data will be removed in a future version. Please use EllipticCurvePublicKey.from_encoded_point
    self.curve, Q_S_bytes

tests/test_wred.py::TestSaiWred::test_wred_create
  /usr/lib/python3/dist-packages/paramiko/kex_ecdh_nist.py:111: CryptographyDeprecationWarning: encode_point has been deprecated on EllipticCurvePublicNumbers and will be removed in a future version. Please use EllipticCurvePublicKey.public_bytes to obtain both compressed and uncompressed point encoding.
    hm.add_string(self.Q_C.public_numbers().encode_point())

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
================================================================================================================================= short test summary info =================================================================================================================================
FAILED test_wred.py::TestSaiWred::test_sai_acl_counter_attr_packets_get - AttributeError: 'NoneType' object has no attribute 'startswith'
========================================================================================================== 1 failed, 2 passed, 97252 deselected, 3 warnings in 70.62s (0:01:10) ===========================================================================================================
root@sai:/sai-challenger/tests# `

**Comment by andriy-kokhan** [comment]
Hm.. You have created WRED object but trying to set/get SAI_ACL_COUNTER_ATTR_PACKETS (ACL attribute). Not sure I understand the idea. Could you please elaborate on this?

**Comment by andriy-kokhan** [comment]
@selldinesh , is this issue still valid?

**Comment by andriy-kokhan** [comment]
Please feel free to re-open in case you still see an issue.
