### ISSUE TITLE
How to interpret results from process_commands, and get OIDs?

### ISSUE THREAD

**Issue by chrispsommers** [opencomputeproject/SAI-Challenger#27]
I am wondering how to interpret the following printout of `results[]` array in a test-case, see CI run https://github.com/Azure/DASH/actions/runs/3661962299/jobs/6190866325#step:22:133
```
======= SAI commands RETURN values =======
[{'switch_id': 0, 'vip': '172.16.1.100'},
 {'switch_id': 0, 'vni': '100'},
 55,
 56,
 57,
 58,
 {'address': '00:CC:CC:CC:00:00', 'switch_id': 0},
 {'destination': '10.1.0.0/16', 'eni_id': 58, 'switch_id': 0},
 {'dip': '10.1.2.50', 'dst_vnet_id': 57, 'switch_id': 0}]
```

Is it possible to see the OIDs returned by SAI layer for every create operation, e.g. embedded in `results`?
Is there a way to access the OID map created during create operations? What is the API inside SAIC?

**Comment by andriy-kokhan** [comment]
It's the result of CRUD APIs execution through `process_commands()` API. In case of `create` operation, it's either `OID` or `Key` for non-OID SAI objects.

Note, for Redis Client, the `create` operation returns either `OID` or `None` for non-OID SAI object. So, some unification should be done here in the future.

In case the objects were created though `Sai.process_commands()`, I believe `Sai.command_processor.objects_registry` can be what you are looking for. No dedicated API at the moment.

@anton7811 , please confirm.

**Comment by chrispsommers** [comment]
Hi @andriy-kokhan thanks for the response.
In case of a create failure, what is the result? I'm looking for a simple assertion expression which I can use regardless of interface (saithrift or sai-redis).

For example, here is an assertion which expects no None objects:
```
assert all(results), "Create Failure"
```

But this would not work for sai-redis if the legitimate result was a key which appears as `None` according to your response.
Do you have a recommended way to check for success of a bunch of creates done via `process_commands()`?

**Comment by chrispsommers** [comment]
Hi @andriy-kokhan could you please see the question above? Still looking for a solid way to check create results, thanks.

**Comment by andriy-kokhan** [comment]
We should check whether both Redis and Thrift interface return the same result/status in the same scenarios. It may happened that at this moment this may require additional validation and unification.
Let me check regarding `process_commands()` results processing. Also, probably @anton7811 can help here.

**Comment by andriy-kokhan** [comment]
Hi @chrispsommers , for each operation `process_commands()` generates one entry in `results[]`. On SAI object create operation, it will be either OID or Key (fdb, route, nat, etc). E.g., https://github.com/opencomputeproject/SAI-Challenger/blob/f987fe6245e319a5fce594d9b030da7a62916ece/tests/test_l2_basic_dd.py#L57 will result:
```
['oid:0x260000000005c9', 'oid:0x270000000005ca', {'bv_id': 'oid:0x260000000005c9', 'mac_address': '00:11:11:11:11:11', 'switch_id': 'oid:0x21000000000000'}, 'oid:0x270000000005cb', {'bv_id': 'oid:0x260000000005c9', 'mac_address': '00:22:22:22:22:22', 'switch_id': 'oid:0x21000000000000'}]
```
To get all the keys/oids created by `process_commands()`, please use `npu.command_processor.objects_registry`.

**Comment by chrispsommers** [comment]
Thanks @andriy-kokhan !
